// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdJeD1ulqJQrm4GHDdX5gjZ_HoBNPU1TI',
    appId: '1:173774811395:web:f85871ac5bef8457687936',
    messagingSenderId: '173774811395',
    projectId: 'gemininew-a7a99',
    authDomain: 'gemininew-a7a99.firebaseapp.com',
    storageBucket: 'gemininew-a7a99.appspot.com',
    measurementId: 'G-DYZLE2PCDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMY_qBicjjpKAo889slCITJ3iMeSDPmzM',
    appId: '1:173774811395:android:1efeab7c0e33da43687936',
    messagingSenderId: '173774811395',
    projectId: 'gemininew-a7a99',
    storageBucket: 'gemininew-a7a99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1E2PwUi_l67w5VsWvQ0c37tiqaw57i08',
    appId: '1:173774811395:ios:ea78014d0a246fc8687936',
    messagingSenderId: '173774811395',
    projectId: 'gemininew-a7a99',
    storageBucket: 'gemininew-a7a99.appspot.com',
    androidClientId: '173774811395-bnufbu0s232e7sfg7mq6gnfc76oklo7f.apps.googleusercontent.com',
    iosClientId: '173774811395-scufk27arki9av6iduicm30caosdgprn.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiAiNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1E2PwUi_l67w5VsWvQ0c37tiqaw57i08',
    appId: '1:173774811395:ios:ea78014d0a246fc8687936',
    messagingSenderId: '173774811395',
    projectId: 'gemininew-a7a99',
    storageBucket: 'gemininew-a7a99.appspot.com',
    androidClientId: '173774811395-bnufbu0s232e7sfg7mq6gnfc76oklo7f.apps.googleusercontent.com',
    iosClientId: '173774811395-scufk27arki9av6iduicm30caosdgprn.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiAiNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdJeD1ulqJQrm4GHDdX5gjZ_HoBNPU1TI',
    appId: '1:173774811395:web:24d914e1bc3186f0687936',
    messagingSenderId: '173774811395',
    projectId: 'gemininew-a7a99',
    authDomain: 'gemininew-a7a99.firebaseapp.com',
    storageBucket: 'gemininew-a7a99.appspot.com',
    measurementId: 'G-5VM5XSSRYB',
  );

}